# Generated by Django 2.2 on 2021-07-05 09:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patient_gynecology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='entrance_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Enterance Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hospital Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Insurance Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='job',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Patient Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='room',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='patient_gynecology',
            name='gynecology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Gynecology', verbose_name='Patient Gynecology'),
        ),
    ]
